### ISSUE TITLE
fatal: I don't handle protocol 'repository: https'

### ISSUE THREAD

**Issue by boticello** [zulu-zsh/zulu#94]
I cannot install or upgrade packages after updating zulu to 1.4.0.
```
zulu install filthy
Failed to clone repository
✘ Error installing filthy
Cloning into 'filthy'...
fatal: I don't handle protocol 'repository: https'
```
I see reference to [a git problem with invisible unicode characters](https://stackoverflow.com/questions/30474447/git-fatal-i-dont-handle-protocol-http) but I don't know if it's related.

**Comment by molovo** [comment]
I don't think that is the issue, since the index is a valid JSON document and an invisible unicode character would fail validation. I think it's more likely that something in your environment has polluted `$IFS`, which prevents the JSON parsing function from reading `repository: "https://..."` as a key and value, and instead returns it as a single line.

Could you please run the failing command again, and immediately after run `echo $IFS | cat -vte
` and paste the output here. That should tell me if `$IFS` has ben set to something other than the default.

I'll try and take a look at the function and see if I can safely override `$IFS` within the parsing function, in which case this would be avoided.

**Comment by molovo** [comment]
I've just created a new branch with a possible fix (if `$IFS` is causing the issue). Could you please check it out by following these steps:

```sh
cd ~/.zulu/core
git fetch origin
git checkout fix_git_protocol_error
./build.zsh

# We need to start in dev mode, because otherwise the master
# branch will be checked out when Zulu is initialised
zulu init --dev
```

After doing that, try installing the package again.

**Comment by boticello** [comment]
Thanks for the quick response and the clear instructions.

I ran an attempted package install and followed it with your command. The output was:
```
 ^I$
^@$
```
I then followed the steps you list. They all seemed to complete successfully.

I ran the `zulu install` command again, and unfortunately had exactly the same response:

```
Failed to clone repository
✘ Error installing filthy
Cloning into 'filthy'...
fatal: I don't handle protocol 'repository: https'
```

**Comment by molovo** [comment]
Hmm. It's not `$IFS` then, since that output is the ZSH default. I'm a little stumped. I have a few questions to help me try and narrow it down:

* What OS and version are you using?
* What ZSH version are you using?
* Do you have any aliases defined for `git`, `sed` or `grep`?
* What is the output of `TEST=$(cat ~/.zulu/index/packages/filthy); jsonval $TEST repository`? (Note: the `jsonval` function is part of Zulu, so you'll need to run it after `zulu init`, in case you've disabled Zulu)

**Comment by boticello** [comment]
I'm using 
- Mac OS 10.12.5
- Zsh 5.2

Aliases in .zshrc:
- `alias grep="grep -n --color"`

The output of the command was:
`_tipz_find_match:23: failed to compile regex: parentheses not balanced` 
(repeated many times)
`repository: https://github.com/molovo/filthy`

**Comment by molovo** [comment]
Ah! The issue is the grep alias you have defined, particularly the `-n` option. Since that adds a line number to the start of each line, it's reading that as the key when parsing the JSON, and the rest as the value. (Unfortunately the JSON parser is very naïve, since it's bloody difficult to do in ZSH).

I've pushed another fix to the `fix_git_protocol_error` branch which ensures it uses the bare command and not an alias. If you follow the steps above again, hopefully the issue should be fixed this time. If it is, I'll publish a new patch tonight.

PS, you can ignore the `_tipz_find_match...` error, that's a different bug in `tipz` which I've just [published a fix for](https://github.com/molovo/tipz/releases/tag/v0.2.2). If you run `zulu upgrade` now that'll be fixed.

**Comment by boticello** [comment]
I pulled the latest code from the `fix_git_protocol_error` branch and ran the commands again, including `zulu init --dev`.

Running `zulu install filthy` now outputs a lot of code but no install information, and the package is not installed.

Since you've identified the problem, I am happy to change the alias for `grep`. That was probably a naïve thing to do in any case. I'm also happy to keep running updated code if you want to troubleshoot the problem further.

Update: I've removed the alias for `grep` and reloaded Zsh with Zulu master branch. The `zulu install filthy` command now works.

**Comment by molovo** [comment]
Hmm, that seems like it might be a different issue. The install works for me, even with the `grep -n` alias defined, and all the tests still pass. Would you mind posting the output?

Removing that alias will definitely resolve your issue short term, but I do plan on fixing this issue properly since aliases such as that are very common. There are calls to system commands throughout Zulu's source, and I should really get around to prefixing all of them with `command` to prevent this sort of thing occurring in future, allowing any aliases to be defined without breaking Zulu. That's a long term fix though

**Comment by boticello** [comment]
OK. I did the following:
```
cd ~/.zulu/core
git checkout fix_git_protocol_error
git pull
zulu init --dev
```
All seemed fine. Then I tried `zulu install spaceship` and it seemed to work:
```
✔ Finished installing spaceship
✔ Theme set to spaceship
✔ Finished linking spaceship
spaceship_git_branch:5: git_current_branch: function definition file not found
spaceship_git_status:16: command not found: git_prompt_status
```
I mean, there are errors. But they seem unrelated. The package installation worked. The output wasn't a dump of the Zsh code as it was before.

I tried `zulu install pure`:
```
✘ Error installing dependency async
fatal: repository 'async' does not exist
Failed to clone repository
✔ Finished installing pure
prompt_pure_setup:24: async: function definition file not found
✔ Theme set to pure
✔ Finished linking pure
prompt_pure_async_tasks:5: command not found: async_start_worker
prompt_pure_async_tasks:6: command not found: async_register_callback
prompt_pure_async_tasks:27: command not found: async_job
```
Again, errors, but seemingly unrelated to the original bug.

Finally, `zulu install rbenv`:
```
✔ Finished installing rbenv
✔ Finished linking rbenv
prompt_pure_async_tasks:27: command not found: async_job
```
So it seems to me that your fix worked, but for some reason until I switched back to master and then back to your fix branch it wasn't working for me. And the situation is slightly confused by the other errors created by the package installs that I tried.

**Comment by molovo** [comment]
Wow, thanks for all this debugging. I think you've managed to hit a couple of different bugs.

It looks like with `spaceship` you simply have a missing dependency, the `git` package. I wasn't aware it was required for that theme, but I'll update the index to add the missing dependency.

The issue with `pure` seems to be a reoccurrence of #88, which I thought I'd fixed. I'll reopen that issue and debug further, and try and recreate it in a test so it won't happen again. The error that appeared after installing `rbenv` is thrown by the `pure` theme because `async` failed to install the first time.

Regarding the original issue, I've just raised PR #95 which prefixes all builtins and important system commands (there's a lot), and that should prevent the kind of alias issues you were having previously (Hopefully!). That should be released in `v1.4.1` fairly soon.

Thanks very much again for your help with debugging this, it's super helpful.

**Comment by boticello** [comment]
Thanks for the praise, but I have a confession. I forgot to uncomment the `grep` alias from my .zshrc when I switched back to the bugfix branch. So my last report is faulty. It was based on running zulu without the cause of the original bug.

When I realised, I switched back to the bugfix branch, uncommented the `grep` alias and did `git pull` because my terminal told me you had made further changes to the branch.

At this point there were merge conflicts, git was being demanding, and I was quickly over my head. I've tried to understand git but it's completely unintuitive to me. So I have somehow wrecked the bugfix branch and can't pull your changes down. I switched back to master and everything is fine (albeit with the need to comment out the grep alias).

I'll try again tomorrow to get a clean version of your bugfix branch and properly establish whether your fix has worked. If you can give me the git command to do that it would help. Otherwise I'll be over to Stack Overflow.

**Comment by molovo** [comment]
Ah, that's my fault. I rebased and force pushed to the branch to prepare it for merging, but that does mean it won't pull nicely due to the history rewrite. To get back to where you were, just checkout the `fix_git_protocol_error` branch and run `git reset --hard origin/fix_git_protocol_error`. Bear in mind, this will reset the entire repository to match the remote, so don't run it if you have any of your own changes in there

**Comment by boticello** [comment]
Everything seemed borked, including the master branch, so I just deleted `.zulu` and installed it again from the website. I lost the	packages I'd installed, but that wasn't a big deal. I installed 'async' first and avoided errors on some of the other packages.

Then I went through the process to reproduce the bug on your up-to-date `fix_git_protocol_error` branch. I'm sorry to confirm that the bug is not fixed and I'm having exactly the same output as the initial bug report.

UPDATE:I switched back to the master branch on this fresh download of 1.4.0, with `grep` still aliased. I tried to install a package ('filthy') and it worked. That is a complete mystery. It doesn't make any sense. Sorry to complicate things further...

**Comment by molovo** [comment]
Hmm, interesting. One last thing to try then, can you try launching ZSH without sourcing your `.zshrc` please?

```
zsh -f
source ~/.zulu/core/zulu
zulu init --dev
```

If the error doesn't occur then, can you post the contents of your `.zshrc` (make sure you redact anything sensitive) so I can try and see what in there is causing the issue? Thanks

**Comment by boticello** [comment]
I did this, and was able to install packages without a problem. Strange.

The only issue worth noting is that the uninstall has some odd warnings. This has been the case throughout my uninstalling of packages since (I guess) the problem first started.

```
❯ zulu uninstall spaceship
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
✔ Finished unlinking spaceship
✔ Finished uninstalling spaceship
 ```

Here is my `.zshrc`:

```


#
# User configuration sourced by interactive shells
#

# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
# Initialise zulu plugin manager
source "${ZULU_DIR:-"${ZDOTDIR:-$HOME}/.zulu"}/core/zulu"
zulu init

# fzf
#export FZFZ_SUBDIR_LIMIT=0
ENHANCD_FILTER=fzf; export ENHANCD_FILTER

# My own settings

setopt appendhistory                    # Append history instead of replacing.
setopt autocd                           # If the given command is a directory switch to it.
setopt beep                             # Beep when a history entry isn't there.
setopt extendedglob                     # Treat #, ~, and, ^ characters as part of the patterns for filename gen.
setopt nomatch                          # Print an error when the filenamepattern has no match.
setopt notify                           # Report job status.

bindkey -v                              # Enable Vi mode.
export KEYTIMEOUT=1

autoload -U zmv                         # load zmv, the renaming function. http://zshwiki.org/home/builtin/functions/zmv

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
# =============================================================================
# Aliases
# =============================================================================

alias cp="nocorrect cp -v"              # Verbose copying with no auto-correct.
alias df="df -h"                        # Enable human-readable output.
alias du='ncdu'                         # Use the Ncdu tool instead of du.
alias grep="grep -n --color"            # Show color and line numbers for match.
alias ht="htop -u $(whoami)"            # Show only my processes.

alias mkdir='nocorrect mkdir'           # No auto-correct when making directory.
alias mv="nocorrect mv -v"              # Verbose moving with no auto-correct.
alias rm="nocorrect rm -v"              # Verbose removing with no auto-correct.

alias -g G="| grep -i --color=NEVER"
```

**Comment by boticello** [comment]
Launching Zsh normally now gives me a new error. I don't know whether I should file this as a separate bug.

```
Last login: Fri Jul 28 08:48:26 on ttys000
_zulu_init_switch_branch:2: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
✔ Switched to Zulu master
_zulu_init_switch_branch:13: command not found: __enhancd::cd
```
I had `enhancd` installed.
I uninstalled it.
I got the following output:
```
❯ zulu uninstall enhancd                                                                                     master
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
✔ Finished unlinking enhancd
✔ Finished uninstalling enhancd
awk: fatal: can't open source file `/Users/xx/.zulu/packages/enhancd/src/share/step_by_step.awk' for reading (No such file or directory)
awk: fatal: can't open source file `/Users/xx/.zulu/packages/enhancd/src/share/step_by_step.awk' for reading (No such file or directory)
```
The awk error line was repeated many times.

Now I get the enhancd error every time I launch the shell, even though it appears to be uninstalled.

When I try to install something with zulu, as well as the https error, I now get this:
```
❯ zulu install enhancd
_zulu_install_package:39: command not found: __enhancd::cd
Failed to clone repository
✘ Error installing enhancd
Cloning into 'enhancd'...
fatal: I don't handle protocol 'repository: https'
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
```
Again, the error lines repeat many times.

**Comment by molovo** [comment]
Ok, so the fact that Zulu worked means that the issue is something in your `.zshrc`. I'm not sure what, but I'll use your `.zshrc` on a test VM and see if I can recreate the issue to try and resolve it for you. The new branch *should* have resolved any of those type of errors, so it could be that I just missed a call somewhere.

I think the errors on uninstall are due to your `rm` alias, but again, that should be prefixed now, so they'll be resolved in the new branch as well (hopefully).

The issue with enhancd looks like something failed in the enhancd package. Not sure why it suddenly appeared to begin with since I'm not hugely familiar with that package, but the errors after you uninstalled it appeared because the main function was still loaded in the environment after it was uninstalled, but the commands it was calling no longer existed. Restarting your session should make those disappear.

I'll get that branch merged into `next` tonight, and then let you know. Once that's done, if you update your `.zshrc` to call `zulu init --next`, instead of just `zulu init` you should at least be able to install and uninstall packages again, and then we can attack anything that's been missed.

**Comment by boticello** [comment]
Thanks. I really appreciate your hard work on this. As you can imagine, the appeal of a framework like Zulu is that someone like me with only modest terminal skills and intermittent need to use the command line can still have a pleasant experience. 

That puts a lot of work on you to make it a smooth experience. Thanks for taking that on board. I think Zulu is a really cool concept and design, and I hope that these snafus can make it even more robust.

**Comment by molovo** [comment]
Yeah, that was exactly who Zulu is aimed at, so these kind of issues need to be fixed. I'm glad you're so willing to help out 👍

**Comment by molovo** [comment]
Ok, I've released `v1.4.1-beta`. If you change your `.zshrc` to call `zulu init --next` now and then restart your shell session, hopefully you should be ok. If not, let me know.

**Comment by boticello** [comment]
I change my `.zshrc` settings as you specified. I didn't do `git pull` or anything else.

Then I started a new shell. (I've pasted the complete output).

```
Last login: Fri Jul 28 11:24:31 on ttys003
_zulu_init_switch_branch:2: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
✔ Switched to Zulu next
_zulu_init_switch_branch:13: command not found: __enhancd::cd

Thanks for using Zulu next
We rely on people like you testing new versions to keep Zulu as useful
and as stable as possible. If you do run into any errors, please do
report them so that they can be fixed before the next release.

Github Issues: https://github.com/zulu-zsh/zulu/issues
Gitter Chat:   https://gitter.im/zulu-zsh/zulu
```
Firstly, I tried to uninstall a package:
```
❯ zulu uninstall warhol
_zulu_unlink:41: command not found: __enhancd::cd
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
_zulu_unlink:41: command not found: __enhancd::cd
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
_zulu_unlink:41: command not found: __enhancd::cd
       unlink file
_zulu_unlink:48: command not found: __enhancd::cd
✔ Finished unlinking warhol
✔ Finished uninstalling warhol
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
```
Then I tried to uninstall enhancd:
```
❯ zulu uninstall enhancd
Package 'enhancd' is not installed
```
Then I tried to reinstall a package:
```
❯ zulu install warhol
'Tipz:' zi warhol
_zulu_install_package:39: command not found: __enhancd::cd
Failed to clone repository
✘ Error installing warhol
Cloning into 'warhol'...
fatal: I don't handle protocol 'repository: https'
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
_zulu_list_packages:35: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:44: command not found: __enhancd::cd
_zulu_list_packages:50: command not found: __enhancd::cd
fatal: Not a git repository (or any of the parent directories): .git
_zulu_list_packages:58: command not found: __enhancd::cd
```
Drat!

**Comment by boticello** [comment]
I logged into my shell this morning and it did not report issues related to `__enhancd`.
```
Last login: Sun Jul 30 07:40:15 on ttys007
_zulu_load_packages:source:4: no such file or directory: /Users/bear/.zulu/packages/warhol/warhol.plugin.zsh

Thanks for using Zulu next
We rely on people like you testing new versions to keep Zulu as useful
and as stable as possible. If you do run into any errors, please do
report them so that they can be fixed before the next release.

Github Issues: https://github.com/zulu-zsh/zulu/issues
Gitter Chat:   https://gitter.im/zulu-zsh/zulu
```
There was that error message related to the `warhol` plugin.

So I tried:
```
❯ zulu install warhol
✔ Finished installing warhol
ln: /Users/bear/.zulu/init/warhol: File exists
✔ Finished linking warhol
```
That was good news! No errors related to `fatal: I don't handle protocol 'repository: https'`.

Then I tried:
```
❯ zulu uninstall warhol
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
usage: rm [-f | -i] [-dPRrvW] file ...
       unlink file
✔ Finished unlinking warhol
✔ Finished uninstalling warhol
```
So, still some kind of error related to my aliasing of `rm`, but nothing fatal.

Looks good!

**Comment by molovo** [comment]
That is good news! Looks like we're nearly there. I'm not sure what's causing those rm errors. I modded the `unlink` command last night to make sure everything is prefixed properly. The rm failing is what caused the `ln: file exists` because the last time you uninstalled the package unlink didn't remove the symlinks that are called to load the package. I'm glad you're able to use it again, but I still want to try and suppress those errors if I can. Haven't had a chance to look at it over the weekend but hopefully I'll find a fix early next week, and then I can publish `v1.4.1`

**Comment by molovo** [comment]
Right, so finally had a chance to play with your `.zshrc` on a VM. The protocol error appeared straight away with a fresh install of Zulu, and switching to `next` got rid of it, so I'm happy that the original issue is resolved. I couldn't recreate those errors with `rm` that you got on uninstall though. You said that you've been getting those ever since you first installed Zulu, is that correct?

**Comment by molovo** [comment]
@boticello would you mind posting the output of `zulu list --installed --branch --tag` please?

**Comment by boticello** [comment]
I was adding to my `.zshrc` during and after installing Zulu. I think the `rm` errors only started at a certain point, which I associated with 1.4.0 but actually could be when I added those aliases to my `.zshrc`.

I've been adding and removing packages as part of the experimentation and debugging. Here's the current output of the command:

```
❯ zulu list --installed --branch --tag
✔ archive
✔ async
✔ color
✔ done
✔ fast-syntax-highlighting
✔ filthy
✔ fzf
✔ fzf-marks
✔ git
✔ history-substring-search
✔ rbenv
✔ revolver
✔ syntax-highlighting
✔ tipz
✔ z
✔ z-cd
✔ zulu-theme
```

**Comment by molovo** [comment]
@boticello sorry I haven't been back to look at this for a while. I still think those `rm` errors are related to the aliases, although I'm not sure why. I'm going to release `v1.4.1` tonight, so at least you can upgrade and get back to using Zulu normally.

It might be related to `xargs`, since the `rm` which is failing is called by that. Do you have anything installed which might modify `xargs`?

**Comment by boticello** [comment]
I don't have anything which modifies `xargs`, to my knowledge.

I've changed my `.zshrc` from `zulu init --next` to `zulu init` and I'll update it tomorrow.

**Comment by molovo** [comment]
@boticello Sorry, ran into another bug which delayed release. `v1.4.1` has been released now. Let me know if you get any further issues.
